package baltimoredata.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GroceryStore generated by hbm2java
 */
@Entity
@Table(name = "grocery_store", catalog = "baltimore_neighborhoods", uniqueConstraints = @UniqueConstraint(columnNames = "address_id"))
public class GroceryStore {

	private Integer id;
	private Address address;
	private GroceryType groceryType;
	private ZipCode zipCode;
	private String name;

	public GroceryStore() {
	}

	public GroceryStore(Address address, GroceryType groceryType, ZipCode zipCode, String name) {
		this.address = address;
		this.groceryType = groceryType;
		this.zipCode = zipCode;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", unique = true, nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type", nullable = false)
	public GroceryType getGroceryType() {
		return this.groceryType;
	}

	public void setGroceryType(GroceryType groceryType) {
		this.groceryType = groceryType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "zipcode", nullable = false)
	public ZipCode getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(ZipCode zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
