package baltimoredata.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

import org.hibernate.validator.constraints.NotBlank;

/**
 * Library generated by hbm2java
 */
@Entity
@Table(name = "library", catalog = "baltimore_neighborhoods", uniqueConstraints = @UniqueConstraint(columnNames = "address_id"))
public class Library {

	private Integer id;
	private Address address;
	private ZipCode zipCode;
	private String name;

	public Library() {
	}

	public Library(Address address, ZipCode zipCode, String name) {
		this.address = address;
		this.zipCode = zipCode;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@Null
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_id", unique = true, nullable = false)
	@NotNull
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "zipcode", nullable = false)
	@NotNull
	public ZipCode getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(ZipCode zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "name", nullable = false)
	@NotBlank
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
