package baltimoredata.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Null;

import org.hibernate.validator.constraints.NotBlank;

/**
 * PoliceDistrict generated by hbm2java
 */
@Entity
@Table(name = "police_district", catalog = "baltimore_neighborhoods", uniqueConstraints = @UniqueConstraint(columnNames = "district_name"))
public class PoliceDistrict {

	private Integer id;
	private String districtName;
	private Set<Address> addresses = new HashSet<Address>(0);

	public PoliceDistrict() {
	}

	public PoliceDistrict(String districtName) {
		this.districtName = districtName;
	}

	public PoliceDistrict(String districtName, Set<Address> addresses) {
		this.districtName = districtName;
		this.addresses = addresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@Null
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "district_name", unique = true, nullable = false)
	@NotBlank
	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "policeDistrict")
	@Null
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
