package baltimoredata.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;

import com.fasterxml.jackson.annotation.JsonView;

import baltimoredata.view.POIViews;

/**
 * ZipCode generated by hbm2java
 */
@Entity
@Table(name = "zip_code", catalog = "baltimore_neighborhoods", uniqueConstraints = @UniqueConstraint(columnNames = "zip"))
public class ZipCode {

	private Integer id;
	private int zip;
	private Set<Library> libraries = new HashSet<Library>(0);
	private Set<GroceryStore> groceryStores = new HashSet<GroceryStore>(0);

	public ZipCode() {
	}

	public ZipCode(int zip) {
		this.zip = zip;
	}

	public ZipCode(int zip, Set<Library> libraries, Set<GroceryStore> groceryStores) {
		this.zip = zip;
		this.libraries = libraries;
		this.groceryStores = groceryStores;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@Null
	@JsonView(POIViews.Minimal.class)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "zip", unique = true, nullable = false)
	@NotNull
	@Min(0)
	@Max(99999)
	@JsonView(POIViews.Minimal.class)
	public int getZip() {
		return this.zip;
	}

	public void setZip(int zip) {
		this.zip = zip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zipCode")
	@Null
	public Set<Library> getLibraries() {
		return this.libraries;
	}

	public void setLibraries(Set<Library> libraries) {
		this.libraries = libraries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zipCode")
	@Null
	public Set<GroceryStore> getGroceryStores() {
		return this.groceryStores;
	}

	public void setGroceryStores(Set<GroceryStore> groceryStores) {
		this.groceryStores = groceryStores;
	}

}
