package baltimoredata;

import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address {

	private Integer id;
	private CouncilDistrict councilDistrict;
	private Neighborhood neighborhood;
	private PoliceDistrict policeDistrict;
	private String streetAddress;
	private Set<Library> libraries = new HashSet<Library>(0);
	private Set<GroceryStore> groceryStores = new HashSet<GroceryStore>(0);
	private Set<Location> locations = new HashSet<Location>(0);

	public Address() {
	}

	public Address(CouncilDistrict councilDistrict, Neighborhood neighborhood, PoliceDistrict policeDistrict) {
		this.councilDistrict = councilDistrict;
		this.neighborhood = neighborhood;
		this.policeDistrict = policeDistrict;
	}

	public Address(CouncilDistrict councilDistrict, Neighborhood neighborhood, PoliceDistrict policeDistrict,
			String streetAddress, Set<Library> libraries, Set<GroceryStore> groceryStores, 
			Set<Location> locations) {
		this.councilDistrict = councilDistrict;
		this.neighborhood = neighborhood;
		this.policeDistrict = policeDistrict;
		this.streetAddress = streetAddress;
		this.libraries = libraries;
		this.groceryStores = groceryStores;
		this.locations = locations;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public CouncilDistrict getCouncilDistrict() {
		return this.councilDistrict;
	}

	public void setCouncilDistrict(CouncilDistrict councilDistrict) {
		this.councilDistrict = councilDistrict;
	}

	public Neighborhood getNeighborhood() {
		return this.neighborhood;
	}

	public void setNeighborhood(Neighborhood neighborhood) {
		this.neighborhood = neighborhood;
	}

	public PoliceDistrict getPoliceDistrict() {
		return this.policeDistrict;
	}

	public void setPoliceDistrict(PoliceDistrict policeDistrict) {
		this.policeDistrict = policeDistrict;
	}

	public String getStreetAddress() {
		return this.streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public Set<Library> getLibraries() {
		return this.libraries;
	}

	public void setLibraries(Set<Library> libraries) {
		this.libraries = libraries;
	}

	public Set<GroceryStore> getGroceryStores() {
		return this.groceryStores;
	}

	public void setGroceryStores(Set<GroceryStore> groceryStores) {
		this.groceryStores = groceryStores;
	}

	public Set<Location> getLocations() {
		return this.locations;
	}

	public void setLocations(Set<Location> locations) {
		this.locations = locations;
	}

}
