package baltimoredata;

import java.util.HashSet;
import java.util.Set;

/**
 * CouncilDistrict generated by hbm2java
 */
public class CouncilDistrict {

	private Integer id;
	private int districtNumber;
	private Set<Address> addresses = new HashSet<Address>(0);

	public CouncilDistrict() {
	}

	public CouncilDistrict(int districtNumber) {
		this.districtNumber = districtNumber;
	}

	public CouncilDistrict(int districtNumber, Set<Address> addresses) {
		this.districtNumber = districtNumber;
		this.addresses = addresses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getDistrictNumber() {
		return this.districtNumber;
	}

	public void setDistrictNumber(int districtNumber) {
		this.districtNumber = districtNumber;
	}

	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
