package baltimoredata;

import java.util.HashSet;
import java.util.Set;

/**
 * GroceryType generated by hbm2java
 */
public class GroceryType {

	private Integer id;
	private String name;
	private Set<GroceryStore> groceryStores = new HashSet<GroceryStore>(0);

	public GroceryType() {
	}

	public GroceryType(String name) {
		this.name = name;
	}

	public GroceryType(String name, Set<GroceryStore> groceryStores) {
		this.name = name;
		this.groceryStores = groceryStores;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<GroceryStore> getGroceryStores() {
		return this.groceryStores;
	}

	public void setGroceryStores(Set<GroceryStore> groceryStores) {
		this.groceryStores = groceryStores;
	}

}
