package baltimoredata;

/**
 * GroceryStore generated by hbm2java
 */
public class GroceryStore {

	private Integer id;
	private Address address;
	private GroceryType groceryType;
	private ZipCode zipCode;
	private String name;

	public GroceryStore() {
	}

	public GroceryStore(Address address, GroceryType groceryType, ZipCode zipCode, String name) {
		this.address = address;
		this.groceryType = groceryType;
		this.zipCode = zipCode;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public GroceryType getGroceryType() {
		return this.groceryType;
	}

	public void setGroceryType(GroceryType groceryType) {
		this.groceryType = groceryType;
	}

	public ZipCode getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(ZipCode zipCode) {
		this.zipCode = zipCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
