package baltimoredata;

/**
 * Library generated by hbm2java
 */
public class Library {

	private Integer id;
	private Address address;
	private ZipCode zipCode;
	private String name;

	public Library() {
	}

	public Library(Address address, ZipCode zipCode, String name) {
		this.address = address;
		this.zipCode = zipCode;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public ZipCode getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(ZipCode zipCode) {
		this.zipCode = zipCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
