package baltimoredata;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location {

	private Integer id;
	private Address address;
	private Serializable coords;
	private String blockNumber;
	private String lotNumber;
	private Set<VacantBuilding> vacantBuildings = new HashSet<VacantBuilding>(0);

	public Location() {
	}

	public Location(Address address, Serializable coords, String blockNumber, String lotNumber) {
		this.address = address;
		this.coords = coords;
		this.blockNumber = blockNumber;
		this.lotNumber = lotNumber;
	}

	public Location(Address address, Serializable coords, String blockNumber, String lotNumber, 
			Set<VacantBuilding> vacantBuildings) {
		this.address = address;
		this.coords = coords;
		this.blockNumber = blockNumber;
		this.lotNumber = lotNumber;
		this.vacantBuildings = vacantBuildings;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Serializable getCoords() {
		return this.coords;
	}

	public void setCoords(Serializable coords) {
		this.coords = coords;
	}

	public String getBlockNumber() {
		return this.blockNumber;
	}

	public void setBlockNumber(String blockNumber) {
		this.blockNumber = blockNumber;
	}

	public String getLotNumber() {
		return this.lotNumber;
	}

	public void setLotNumber(String lotNumber) {
		this.lotNumber = lotNumber;
	}

	public Set<VacantBuilding> getVacantBuildings() {
		return this.vacantBuildings;
	}

	public void setVacantBuildings(Set<VacantBuilding> vacantBuildings) {
		this.vacantBuildings = vacantBuildings;
	}

}
