package baltimoredata;

import java.util.HashSet;
import java.util.Set;

/**
 * Neighborhood generated by hbm2java
 */
public class Neighborhood {

	private Integer id;
	private Area area;
	private String name;
	private Set<Address> addresses = new HashSet<Address>(0);

	public Neighborhood() {
	}

	public Neighborhood(Area area, String name) {
		this.area = area;
		this.name = name;
	}

	public Neighborhood(Area area, String name, Set<Address> addresses) {
		this.area = area;
		this.name = name;
		this.addresses = addresses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
