package baltimoredata;

import java.util.HashSet;
import java.util.Set;

/**
 * PoliceDistrict generated by hbm2java
 */
public class PoliceDistrict {

	private Integer id;
	private String districtName;
	private Set<Address> addresses = new HashSet<Address>(0);

	public PoliceDistrict() {
	}

	public PoliceDistrict(String districtName) {
		this.districtName = districtName;
	}

	public PoliceDistrict(String districtName, Set<Address> addresses) {
		this.districtName = districtName;
		this.addresses = addresses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
