package baltimoredata;

import java.util.Date;

/**
 * VacantBuilding generated by hbm2java
 */
public class VacantBuilding {

	private Integer id;
	private Location location;
	private String referenceid;
	private Date noticedate;

	public VacantBuilding() {
	}

	public VacantBuilding(Location location, String referenceid, Date noticedate) {
		this.location = location;
		this.referenceid = referenceid;
		this.noticedate = noticedate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getReferenceid() {
		return this.referenceid;
	}

	public void setReferenceid(String referenceid) {
		this.referenceid = referenceid;
	}

	public Date getNoticedate() {
		return this.noticedate;
	}

	public void setNoticedate(Date noticedate) {
		this.noticedate = noticedate;
	}

}
