package baltimoredata;

import java.util.HashSet;
import java.util.Set;

/**
 * ZipCode generated by hbm2java
 */
public class ZipCode {

	private Integer id;
	private int zip;
	private Set<Library> libraries = new HashSet<Library>(0);
	private Set<GroceryStore> groceryStores = new HashSet<GroceryStore>(0);

	public ZipCode() {
	}

	public ZipCode(int zip) {
		this.zip = zip;
	}

	public ZipCode(int zip, Set<Library> libraries, Set<GroceryStore> groceryStores) {
		this.zip = zip;
		this.libraries = libraries;
		this.groceryStores = groceryStores;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getZip() {
		return this.zip;
	}

	public void setZip(int zip) {
		this.zip = zip;
	}

	public Set<Library> getLibraries() {
		return this.libraries;
	}

	public void setLibraries(Set<Library> libraries) {
		this.libraries = libraries;
	}

	public Set<GroceryStore> getGroceryStores() {
		return this.groceryStores;
	}

	public void setGroceryStores(Set<GroceryStore> groceryStores) {
		this.groceryStores = groceryStores;
	}

}
